import { Supplier } from './types';

export const INITIAL_SUPPLIERS: Supplier[] = [
  {
    id: 'sup-1',
    companyName: 'Acme Corp',
    contactName: 'Jane Doe',
    email: 'jane.doe@acme.com',
    phone: '+1 (555) 123-4567',
    productsSupplied: ['Electronics', 'Hardware', 'Networking'],
    status: 'Active',
    initials: 'AC',
    initialsBg: 'bg-blue-100 text-blue-700',
    joinedDate: '2022-03-15',
  },
  {
    id: 'sup-2',
    companyName: 'Global Tech Supplies',
    contactName: 'John Smith',
    email: 'jsmith@globaltech.com',
    phone: '+44 20 7123 4567',
    productsSupplied: ['Software', 'Cloud'],
    status: 'Pending',
    initials: 'GT',
    initialsBg: 'bg-amber-100 text-amber-700',
    joinedDate: '2023-07-01',
  },
  {
    id: 'sup-3',
    companyName: 'Apex Materials Ltd.',
    contactName: 'Sarah Jenkins',
    email: 's.jenkins@apexmaterials.com',
    phone: '+1 (800) 987-6543',
    productsSupplied: ['Raw Materials'],
    status: 'Inactive',
    initials: 'AM',
    initialsBg: 'bg-red-100 text-red-700',
    joinedDate: '2021-11-20',
  },
  {
    id: 'sup-4',
    companyName: 'Logistics Pro',
    contactName: 'Michael Chen',
    email: 'mchen@logisticspro.io',
    phone: '+65 6123 4567',
    productsSupplied: ['Shipping', 'Packaging'],
    status: 'Active',
    initials: 'LP',
    initialsBg: 'bg-emerald-100 text-emerald-700',
    joinedDate: '2022-08-10',
  },
  {
    id: 'sup-5',
    companyName: 'NovaParts Inc.',
    contactName: 'Elena Rodriguez',
    email: 'e.rodriguez@novaparts.com',
    phone: '+1 (555) 302-9912',
    productsSupplied: ['Peripherals', 'Hardware', 'Storage'],
    status: 'Active',
    initials: 'NP',
    initialsBg: 'bg-purple-100 text-purple-700',
    joinedDate: '2023-01-05',
  },
  {
    id: 'sup-6',
    companyName: 'SteelFrame Co.',
    contactName: 'David Kim',
    email: 'dkim@steelframe.co',
    phone: '+1 (555) 883-2019',
    productsSupplied: ['Metals', 'Raw Materials'],
    status: 'Active',
    initials: 'SF',
    initialsBg: 'bg-slate-100 text-slate-700',
    joinedDate: '2022-05-18',
  },
  {
    id: 'sup-7',
    companyName: 'ChemSource Global',
    contactName: 'Olivia Turner',
    email: 'o.turner@chemsource.com',
    phone: '+49 30 1234 5678',
    productsSupplied: ['Chemicals', 'Lab Supplies'],
    status: 'Pending',
    initials: 'CG',
    initialsBg: 'bg-orange-100 text-orange-700',
    joinedDate: '2024-02-28',
  },
  {
    id: 'sup-8',
    companyName: 'ByteStream Systems',
    contactName: 'Marcus Vance',
    email: 'm.vance@bytestream.dev',
    phone: '+1 (555) 492-1102',
    productsSupplied: ['Software', 'Electronics', 'Networking'],
    status: 'Active',
    initials: 'BS',
    initialsBg: 'bg-indigo-100 text-indigo-700',
    joinedDate: '2023-04-12',
  },
  {
    id: 'sup-9',
    companyName: 'PrimePack Solutions',
    contactName: 'Chloe Bennett',
    email: 'cbennett@primepack.com',
    phone: '+1 (555) 219-5540',
    productsSupplied: ['Packaging', 'Labels'],
    status: 'Inactive',
    initials: 'PP',
    initialsBg: 'bg-pink-100 text-pink-700',
    joinedDate: '2021-09-30',
  },
  {
    id: 'sup-10',
    companyName: 'Vanguard Components',
    contactName: 'Sophia Martinez',
    email: 'smartinez@vanguardcomp.io',
    phone: '+1 (555) 721-9043',
    productsSupplied: ['Electronics', 'Hardware'],
    status: 'Active',
    initials: 'VC',
    initialsBg: 'bg-cyan-100 text-cyan-700',
    joinedDate: '2022-12-01',
  },
];
