import { Order } from './types';

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord-1',
    orderNumber: '#ORD-1234',
    customer: { name: 'Acme Corp', initials: 'AC', initialsBg: 'bg-blue-100 text-blue-700' },
    date: 'Oct 24, 2023',
    items: 12,
    total: 4500.00,
    paymentStatus: 'Paid',
    status: 'Processing',
  },
  {
    id: 'ord-2',
    orderNumber: '#ORD-1235',
    customer: { name: 'Global Ind.', initials: 'GI', initialsBg: 'bg-emerald-100 text-emerald-700' },
    date: 'Oct 24, 2023',
    items: 3,
    total: 850.50,
    paymentStatus: 'Paid',
    status: 'Shipped',
  },
  {
    id: 'ord-3',
    orderNumber: '#ORD-1236',
    customer: { name: 'Stark LLC', initials: 'S', initialsBg: 'bg-slate-100 text-slate-700' },
    date: 'Oct 23, 2023',
    items: 45,
    total: 12400.00,
    paymentStatus: 'Pending',
    status: 'Pending',
  },
  {
    id: 'ord-4',
    orderNumber: '#ORD-1237',
    customer: { name: 'Wayne Ent.', initials: 'W', initialsBg: 'bg-purple-100 text-purple-700' },
    date: 'Oct 22, 2023',
    items: 1,
    total: 250.00,
    paymentStatus: 'Failed',
    status: 'Cancelled',
  },
  {
    id: 'ord-5',
    orderNumber: '#ORD-1238',
    customer: { name: 'Oscorp', initials: 'O', initialsBg: 'bg-orange-100 text-orange-700' },
    date: 'Oct 21, 2023',
    items: 8,
    total: 3100.25,
    paymentStatus: 'Paid',
    status: 'Delivered',
  },
  {
    id: 'ord-6',
    orderNumber: '#ORD-1239',
    customer: { name: 'Nexus Mfg', initials: 'NM', initialsBg: 'bg-indigo-100 text-indigo-700' },
    date: 'Oct 20, 2023',
    items: 20,
    total: 9870.00,
    paymentStatus: 'Paid',
    status: 'Delivered',
  },
  {
    id: 'ord-7',
    orderNumber: '#ORD-1240',
    customer: { name: 'Vanguard Sys.', initials: 'VS', initialsBg: 'bg-cyan-100 text-cyan-700' },
    date: 'Oct 19, 2023',
    items: 6,
    total: 2200.75,
    paymentStatus: 'Refunded',
    status: 'Cancelled',
  },
  {
    id: 'ord-8',
    orderNumber: '#ORD-1241',
    customer: { name: 'Apex Innovations', initials: 'AI', initialsBg: 'bg-amber-100 text-amber-700' },
    date: 'Oct 18, 2023',
    items: 15,
    total: 6750.00,
    paymentStatus: 'Paid',
    status: 'Shipped',
  },
  {
    id: 'ord-9',
    orderNumber: '#ORD-1242',
    customer: { name: 'ByteStream', initials: 'BS', initialsBg: 'bg-pink-100 text-pink-700' },
    date: 'Oct 17, 2023',
    items: 4,
    total: 1125.50,
    paymentStatus: 'Pending',
    status: 'Processing',
  },
  {
    id: 'ord-10',
    orderNumber: '#ORD-1243',
    customer: { name: 'Horizon Health', initials: 'HH', initialsBg: 'bg-teal-100 text-teal-700' },
    date: 'Oct 16, 2023',
    items: 9,
    total: 4300.00,
    paymentStatus: 'Paid',
    status: 'Delivered',
  },
  {
    id: 'ord-11',
    orderNumber: '#ORD-1244',
    customer: { name: 'TechSolutions', initials: 'TS', initialsBg: 'bg-violet-100 text-violet-700' },
    date: 'Oct 15, 2023',
    items: 2,
    total: 599.99,
    paymentStatus: 'Failed',
    status: 'Cancelled',
  },
  {
    id: 'ord-12',
    orderNumber: '#ORD-1245',
    customer: { name: 'Starlight Ret.', initials: 'SR', initialsBg: 'bg-rose-100 text-rose-700' },
    date: 'Oct 14, 2023',
    items: 30,
    total: 14200.00,
    paymentStatus: 'Paid',
    status: 'Processing',
  },
  {
    id: 'ord-13',
    orderNumber: '#ORD-1246',
    customer: { name: 'NovaParts Inc.', initials: 'NP', initialsBg: 'bg-lime-100 text-lime-700' },
    date: 'Oct 13, 2023',
    items: 7,
    total: 2950.00,
    paymentStatus: 'Paid',
    status: 'Shipped',
  },
  {
    id: 'ord-14',
    orderNumber: '#ORD-1247',
    customer: { name: 'SteelFrame Co.', initials: 'SF', initialsBg: 'bg-stone-100 text-stone-700' },
    date: 'Oct 12, 2023',
    items: 18,
    total: 8100.50,
    paymentStatus: 'Pending',
    status: 'Pending',
  },
  {
    id: 'ord-15',
    orderNumber: '#ORD-1248',
    customer: { name: 'Logistics Pro', initials: 'LP', initialsBg: 'bg-sky-100 text-sky-700' },
    date: 'Oct 11, 2023',
    items: 11,
    total: 5300.00,
    paymentStatus: 'Paid',
    status: 'Delivered',
  },
];
