import { Product } from './types';

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    name: 'Industrial Router Series X',
    sku: 'NET-RT-X900',
    category: 'Networking',
    price: 1299.00,
    stock: 425,
    stockStatus: 'In Stock',
    image: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&q=80&w=120',
    description: 'High-speed industrial grade router with dual-band failover capability.',
  },
  {
    id: 'prod-2',
    name: 'Modular Server Chassis',
    sku: 'SRV-CH-M44',
    category: 'Hardware',
    price: 3450.00,
    stock: 12,
    stockStatus: 'Low Stock',
    image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&q=80&w=120',
    description: '4U rackmount modular chassis supporting hot-swappable drive bays.',
  },
  {
    id: 'prod-3',
    name: 'Enterprise SSD 4TB',
    sku: 'STG-SSD-4T-PRO',
    category: 'Storage',
    price: 599.99,
    stock: 0,
    stockStatus: 'Out of Stock',
    image: 'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?auto=format&fit=crop&q=80&w=120',
    description: 'Ultra-fast enterprise NVMe SSD built for high endurance database workloads.',
  },
  {
    id: 'prod-4',
    name: 'Ergonomic Keyboard V2',
    sku: 'PER-KB-ERGO2',
    category: 'Peripherals',
    price: 149.00,
    stock: 850,
    stockStatus: 'In Stock',
    image: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&q=80&w=120',
    description: 'Split mechanical ergonomic keyboard with programmable macro switches.',
  },
  {
    id: 'prod-5',
    name: '4K Ultra HD Monitor 32"',
    sku: 'DIS-4K-32PRO',
    category: 'Peripherals',
    price: 799.00,
    stock: 54,
    stockStatus: 'In Stock',
    image: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&q=80&w=120',
    description: 'IPS color-accurate 4K monitor designed for workstation professionals.',
  },
  {
    id: 'prod-6',
    name: 'Rackmount Switch 48-Port',
    sku: 'NET-SW-48P',
    category: 'Networking',
    price: 1850.00,
    stock: 5,
    stockStatus: 'Low Stock',
    image: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&q=80&w=120',
    description: 'Managed 48-port PoE+ enterprise switch with 10G SFP+ uplinks.',
  },
  {
    id: 'prod-7',
    name: 'High-Performance RAM 64GB',
    sku: 'MEM-DDR5-64G',
    category: 'Hardware',
    price: 320.00,
    stock: 0,
    stockStatus: 'Out of Stock',
    image: 'https://images.unsplash.com/photo-1562976540-1502c2145186?auto=format&fit=crop&q=80&w=120',
    description: 'Dual-channel DDR5 server memory kit running at 5600MHz.',
  },
  {
    id: 'prod-8',
    name: 'NVMe PCIe Gen4 SSD 2TB',
    sku: 'STG-NVME-2T',
    category: 'Storage',
    price: 249.99,
    stock: 120,
    stockStatus: 'In Stock',
    image: 'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?auto=format&fit=crop&q=80&w=120',
    description: 'Gen4 x4 M.2 solid state drive with aluminum heatsink.',
  },
];
