import { User } from './types';

export const INITIAL_USERS: User[] = [
  {
    id: 'usr-1',
    name: 'Jane Cooper',
    email: 'jane.cooper@example.com',
    role: 'Admin',
    status: 'Active',
    created: 'Jan 12, 2024',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=120',
  },
  {
    id: 'usr-2',
    name: 'Cody Fisher',
    email: 'cody.fisher@example.com',
    role: 'Editor',
    status: 'Active',
    created: 'Jan 15, 2024',
    initials: 'CF',
    initialsBg: 'bg-blue-100 text-blue-700',
  },
  {
    id: 'usr-3',
    name: 'Esther Howard',
    email: 'esther.howard@example.com',
    role: 'Viewer',
    status: 'Suspended',
    created: 'Feb 02, 2024',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&q=80&w=120',
  },
  {
    id: 'usr-4',
    name: 'Jenny Wilson',
    email: 'jenny.wilson@example.com',
    role: 'Editor',
    status: 'Inactive',
    created: 'Mar 10, 2024',
    initials: 'JW',
    initialsBg: 'bg-purple-100 text-purple-700',
  },
  {
    id: 'usr-5',
    name: 'Robert Fox',
    email: 'robert.fox@example.com',
    role: 'Manager',
    status: 'Active',
    created: 'Mar 22, 2024',
    initials: 'RF',
    initialsBg: 'bg-emerald-100 text-emerald-700',
  },
  {
    id: 'usr-6',
    name: 'Kristin Watson',
    email: 'kristin.watson@example.com',
    role: 'Admin',
    status: 'Active',
    created: 'Apr 01, 2024',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=120',
  },
  {
    id: 'usr-7',
    name: 'Cameron Williamson',
    email: 'c.williamson@example.com',
    role: 'Viewer',
    status: 'Inactive',
    created: 'Apr 08, 2024',
    initials: 'CW',
    initialsBg: 'bg-amber-100 text-amber-700',
  },
  {
    id: 'usr-8',
    name: 'Brooklyn Simmons',
    email: 'brooklyn.s@example.com',
    role: 'Editor',
    status: 'Active',
    created: 'Apr 14, 2024',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=120',
  },
  {
    id: 'usr-9',
    name: 'Leslie Alexander',
    email: 'l.alexander@example.com',
    role: 'Manager',
    status: 'Suspended',
    created: 'May 03, 2024',
    initials: 'LA',
    initialsBg: 'bg-rose-100 text-rose-700',
  },
  {
    id: 'usr-10',
    name: 'Floyd Miles',
    email: 'floyd.miles@example.com',
    role: 'Viewer',
    status: 'Active',
    created: 'May 20, 2024',
    initials: 'FM',
    initialsBg: 'bg-cyan-100 text-cyan-700',
  },
  {
    id: 'usr-11',
    name: 'Darrell Steward',
    email: 'd.steward@example.com',
    role: 'Admin',
    status: 'Active',
    created: 'Jun 01, 2024',
    initials: 'DS',
    initialsBg: 'bg-indigo-100 text-indigo-700',
  },
  {
    id: 'usr-12',
    name: 'Guy Hawkins',
    email: 'guy.hawkins@example.com',
    role: 'Editor',
    status: 'Inactive',
    created: 'Jun 15, 2024',
    initials: 'GH',
    initialsBg: 'bg-slate-100 text-slate-600',
  },
];
